baseURL = "https://helberth.github.io/amedev-docs/"
languageCode = "en-us"
title = "Amedev Docs"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'
  homepage_intro = 'This is documentation for AME Learning Dev Team'
  # homepage_image = '/images/terminal.gif'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "AME Learning Dev documentation."
    meta_og_title = "AME Learning Dev documentation."
    meta_og_type = "website"
    meta_og_url = "https://hugo-whisper.netlify.app"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-whisper-theme/master/images/tn.png"
    meta_og_description = "AME Learning Dev documentation."
    meta_twitter_card = "summary"
    meta_twitter_site = "@helberth_espin"
    meta_twitter_creator = "@helberth_espin"

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/images/logo.svg"
